export const FACTORY_CONTRAC_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_mlc', type: 'address' },
      { internalType: 'uint192', name: '_mlcPerBlock', type: 'uint192' },
      { internalType: 'uint32', name: '_blocksPerUpdate', type: 'uint32' },
      { internalType: 'uint32', name: '_initBlock', type: 'uint32' },
      { internalType: 'uint32', name: '_endBlock', type: 'uint32' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_by', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newMtlPerBlock', type: 'uint256' },
    ],
    name: 'MtlRatioUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_by', type: 'address' },
      { indexed: true, internalType: 'address', name: 'poolToken', type: 'address' },
      { indexed: true, internalType: 'address', name: 'poolAddress', type: 'address' },
      { indexed: false, internalType: 'uint64', name: 'weight', type: 'uint64' },
      { indexed: false, internalType: 'bool', name: 'isFlashPool', type: 'bool' },
    ],
    name: 'PoolRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: '_by', type: 'address' },
      { indexed: true, internalType: 'address', name: 'poolAddress', type: 'address' },
      { indexed: false, internalType: 'uint32', name: 'weight', type: 'uint32' },
    ],
    name: 'WeightUpdated',
    type: 'event',
  },
  {
    inputs: [],
    name: 'blocksPerUpdate',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'poolAddr', type: 'address' },
      { internalType: 'uint32', name: 'weight', type: 'uint32' },
    ],
    name: 'changePoolWeight',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'endBlock',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'poolToken', type: 'address' }],
    name: 'getPoolAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_poolToken', type: 'address' }],
    name: 'getPoolData',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'poolToken', type: 'address' },
          { internalType: 'address', name: 'poolAddress', type: 'address' },
          { internalType: 'uint32', name: 'weight', type: 'uint32' },
          { internalType: 'bool', name: 'isFlashPool', type: 'bool' },
        ],
        internalType: 'struct MetalifePoolFactory.PoolData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastRatioUpdate',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'mintYieldTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mlc',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mlcPerBlock',
    outputs: [{ internalType: 'uint192', name: '', type: 'uint192' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'poolExists',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'pools',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'poolAddr', type: 'address' }],
    name: 'registerPool',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'shouldUpdateRatio',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalWeight',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'updateMLCPerBlock', outputs: [], stateMutability: 'nonpayable', type: 'function' },
];
